disabled_rules: # rule identifiers to exclude
    - colon
    - trailing_whitespace
    - operator_usage_whitespace
    - line_length
    - implicitly_unwrapped_optional # will throw an error for outlets. Hence disabling

opt_in_rules:
    - array_init
    - closing_brace
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - closure_parameter_position
    - cyclomatic_complexity
    - discouraged_object_literal
    - empty_count
    - empty_string
    - explicit_init
    - force_unwrapping
    - function_body_length
    - identifier_name
    - implicit_return
    - let_var_whitespace
    - literal_expression_end_indentation
    - multiline_arguments
    - overridden_super_call
    - private_action
    - private_outlet
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - redundant_nil_coalescing
    - required_enum_case
    - trailing_semicolon
    - single_test_class
    - sorted_first_last
    - statement_position
    - file_length
    - switch_case_on_newline
    - toggle_bool
    - unowned_variable_capture
    - unneeded_parentheses_in_closure_argument
    - unused_declaration
    - unused_import
    - vertical_parameter_alignment_on_call
    - weak_delegate
    - yoda_condition

excluded:
    - Pods
    - Frameworks
    - SignatureAviationTests
    - SignatureAviationUITests
    - Products

# Customize behaviour of the existing rules
nesting:
    type_level: 2
    statement_level: 5

type_body_length:
    - 400 # warning
    - 500 # error

file_length:
    - 500 # warning
    - 600 # error
